version: '3'

services:
#  mariadb:
#    image: mariadb:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: douzone_test
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
#    ports:
#      - "3307:3306"

  spring-boot-app:
    image: wonyong92/spring:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - back-db
    ports:
      - "8080:8080"
  back-db:
    image: wonyong92/maria:latest
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "3307:3306"